version: '2'

volumes:
  mongo_data: {}

services:
  node:
    restart: always
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
      args:
        NODE_ENV: production
    environment:
      DATABASE_URL: "mongodb://mongo:27017/lubi-cafe"
    volumes:
      - /home/node/app/uploads
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:3.4.10
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile_dev
    volumes_from:
      - node
    depends_on:
      - node
    ports:
      - "80:80"