version: '2'

volumes:
  mongo_data: {}
  mongo_backup: {}

services:
  node:
    # restart: always
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile_dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "mongodb://mongo:27017/loopback-docker-boilerplate"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/storage
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:3
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/backups
    ports:
     - '127.0.0.1:27017:27017'
